term.setTextColor(colors.yellow)
print("MineOs 1.0 on " .. _HOST)
term.setTextColor(colors.white)
print("If you wanna learn about new feature type: \"new\"")
print("If you want to disable this os is hard or you will go to my website https://sites.google.com/view/mineosdocs")