term.setTextColor(colors.yellow)
print("Some new thing to you\n")
print("lib - A new api to make libbarys easyer to import.")
term.setTextColor(colors.white)
print("More info:https://sites.google.com/view/mineosdocs")